name: journal_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  table_calendar: ^3.1.2
  hive_flutter: ^1.1.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  shared_preferences: ^2.3.1
  timezone: ^0.9.4
  intl: ^0.19.0
  stage_navigation_bar: ^0.1.0
  flutter_local_notifications: ^17.2.2
  workmanager: ^0.5.2
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^26.2.9
  flutter_sound: ^9.1.1
  audio_session: ^0.1.21
  path_provider: ^2.1.4
  audioplayers: ^5.2.1
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.7.0
  awesome_bottom_bar: ^1.2.4
  file_picker: ^8.1.2
  package_info_plus: ^8.0.2
  hive: ^2.2.3
  flutter_sound_platform_interface: ^9.6.0
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Images/diary.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/Images/mood.png
    - assets/Images/diary.png
    - assets/Images/journal1.jpg
    - assets/Images/mood2.jpg
    - assets/Images/calendar5.jpg
    - assets/Images/calendar6 .jpg
    - assets/fonts/

  fonts:
    - family: AlwaysForever
      fonts:
        - asset: assets/fonts/always forever.ttf
    - family: AngelineVintage
      fonts:
        - asset: assets/fonts/Angeline Vintage_Demo.otf
    - family: Bearsville
      fonts:
        - asset: assets/fonts/BearsvilleDemoRegular.ttf
    - family: Castlenight
      fonts:
        - asset: assets/fonts/Castlenight DEMO VERSION.otf
        - asset: assets/fonts/Castlenight Italic DEMO VERSION.otf
          style: italic
    - family: Dolemy
      fonts:
        - asset: assets/fonts/Dolemy Font DEMO.ttf
    - family: Gailla
      fonts:
        - asset: assets/fonts/GaillaDemoRegular.ttf
    - family: Jacksboro
      fonts:
        - asset: assets/fonts/JacksboroDemoRegular.ttf
    - family: RabbitShow
      fonts:
        - asset: assets/fonts/RabbitShowDemoRegular.ttf
    - family: Rainday
      fonts:
        - asset: assets/fonts/Rainday.otf
    - family: Baltijens
      fonts:
        - asset: assets/fonts/Baltijens Demo.otf
    - family: Ordinals
      fonts:
        - asset: assets/fonts/Monthy Ordinals Serif DEMO.otf
    - family: Salsify
      fonts:
        - asset: assets/fonts/Salsify DEMO.otf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
    - family: Nunito1
      fonts:
        - asset: assets/fonts/Nunito-BlackItalic.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-black.ttf
    - family: Montserrat-Black
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
    - family: Montserrat-Black1
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Nunito2
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: NexaDemo
      fonts:
        - asset: assets/fonts/NexaDemo-Light.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Opensans
      fonts:
        - asset: assets/fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
    - family: Opensans2
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
    - family: Montserrat-Thin
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
    
    

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
